# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

# Fallback
monitor=,preferred,auto,auto

# Laptop
monitor=eDP-1,3000x2000@60,auto,2
