# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

# Fallback
monitor=,preferred,auto,auto

# Laptop
monitor=eDP-1,2880x1920@120,0x0,2
