-- generated by Noctalia, do not edit
return {
  active   = "rgba({{ colors.primary.default.hex_stripped }}ff)",
  inactive = "rgba({{ colors.outline.default.hex_stripped }}aa)",
  locked   = "rgba({{ colors.tertiary.default.hex_stripped }}ff)",
}
